# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [17]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json
import time

# Import API key
#from api_keys import g_key

#### NOTE: Importing g_key from the api_keys file was not working properly. Please manually enter your own gmaps api key where indicated below to make the kernals run properly. Search "Enter gkey" to find all necessary input areas.

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [4]:
weather_data = pd.read_csv("output_data/cities2.csv")
weather_data

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,Rikitea,77,PF,1604262409,86,-23.12,-134.97,74.55,22.30
1,La Rioja,0,ES,1604262550,87,42.25,-2.50,60.01,7.43
2,Punta Arenas,75,CL,1604262550,76,-53.15,-70.92,51.80,14.99
3,Praia da Vitória,75,PT,1604262550,100,38.73,-27.07,64.00,18.21
4,Cabo San Lucas,43,MX,1604262524,38,22.89,-109.91,90.00,4.00
...,...,...,...,...,...,...,...,...,...
1127,Salym,98,RU,1604262572,97,60.06,71.48,29.95,8.52
1128,Springfield,1,US,1604262303,27,37.22,-93.30,55.00,13.87
1129,North Vanlaiphai,73,IN,1604262572,100,23.13,93.07,58.03,1.48
1130,Labuhan,69,ID,1604262572,83,-6.88,112.21,77.70,4.47
1131,Turaif,75,SA,1604262573,93,31.67,38.66,60.80,25.28

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [7]:
# Configure gmaps
gmaps.configure(api_key="Enter gkey")

# Store latitude and longitude in locations
locations = weather_data[["Lat", "Lng"]]

# Store Humidity in humidity
humidity = weather_data["Humidity"]

In [8]:
# Plot Heatmap
fig = gmaps.figure(center=(46.0, -5.0), zoom_level=2)
max_intensity = np.max(humidity)

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights = humidity, dissipating=False, max_intensity=100, point_radius=3)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
max_intensity

100

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [11]:
# Narrow down the cities with wind speed less than 10 mph, cloudiness equals to 0 and max temp between 65 and 78
narrowed_city_df = weather_data.loc[(weather_data["Wind Speed"] <= 10) & (weather_data["Cloudiness"] == 0) & \
                                   (weather_data["Max Temp"] >= 65) & (weather_data["Max Temp"] <= 78)].dropna()

narrowed_city_df

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
101,Valdivia,0,CL,1604262554,53,-39.81,-73.25,71.60,9.17
108,Salalah,0,OM,1604262554,69,17.02,54.09,77.00,2.24
171,Tando Muhammad Khan,0,PK,1604262557,20,25.12,68.54,75.78,4.99
219,Saldanha,0,ZA,1604262558,56,-33.01,17.94,68.00,5.82
240,Victoria Point,0,AU,1604262559,74,-27.58,153.30,71.01,5.99
265,Buraidah,0,SA,1604262560,37,26.33,43.98,69.80,6.93
290,Sabha,0,LY,1604262561,51,27.04,14.43,65.19,8.68
353,Dehlorān,0,IR,1604262564,23,32.69,47.27,68.65,5.41
365,Khanpur,0,PK,1604262565,23,28.65,70.66,65.55,4.90
378,Mangrūl Pīr,0,IN,1604262544,60,20.32,77.35,69.96,2.01
408,Los Llanos de Aridane,0,ES,1604262416,25,28.66,-17.92,77.00,6.93
422,Charters Towers,0,AU,1604262567,83,-20.10,146.27,69.80,7.43
499,Mae Sai,0,TH,1604262570,100,20.43,99.88,71.01,1.12
515,Karwar,0,IN,1604262571,79,14.80,74.13,76.71,4.00
533,Sur,0,OM,1604262571,43,22.57,59.53,70.61,4.36
547,Taunsa,0,PK,1604262572,23,30.70,70.65,65.70,3.89
555,Tiznit Province,0,MA,1604262448,28,29.58,-9.50,71.87,1.88
667,Valdivia,0,CL,1604262554,53,-39.81,-73.25,71.60,9.17
674,Salalah,0,OM,1604262554,69,17.02,54.09,77.00,2.24
737,Tando Muhammad Khan,0,PK,1604262557,20,25.12,68.54,75.78,4.99
785,Saldanha,0,ZA,1604262558,56,-33.01,17.94,68.00,5.82
806,Victoria Point,0,AU,1604262559,74,-27.58,153.30,71.01,5.99
831,Buraidah,0,SA,1604262560,37,26.33,43.98,69.80,6.93
856,Sabha,0,LY,1604262561,51,27.04,14.43,65.19,8.68
919,Dehlorān,0,IR,1604262564,23,32.69,47.27,68.65,5.41
931,Khanpur,0,PK,1604262565,23,28.65,70.66,65.55,4.90
944,Mangrūl Pīr,0,IN,1604262544,60,20.32,77.35,69.96,2.01
974,Los Llanos de Aridane,0,ES,1604262416,25,28.66,-17.92,77.00,6.93
988,Charters Towers,0,AU,1604262567,83,-20.10,146.27,69.80,7.43
1065,Mae Sai,0,TH,1604262570,100,20.43,99.88,71.01,1.12
1081,Karwar,0,IN,1604262571,79,14.80,74.13,76.71,4.00
1099,Sur,0,OM,1604262571,43,22.57,59.53,70.61,4.36
1113,Taunsa,0,PK,1604262572,23,30.70,70.65,65.70,3.89
1121,Tiznit Province,0,MA,1604262448,28,29.58,-9.50,71.87,1.88

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [12]:
# Create a hotel_df
hotel_df = narrowed_city_df.loc[:,["City","Country", "Lat", "Lng"]]

# Add a "Hotel Name" column to the DataFrame.
hotel_df["Hotel Name"] = ""

# Display the result
hotel_df

                       City Country    Lat     Lng Hotel Name
101                Valdivia      CL -39.81  -73.25
108                 Salalah      OM  17.02   54.09
171     Tando Muhammad Khan      PK  25.12   68.54
219                Saldanha      ZA -33.01   17.94
240          Victoria Point      AU -27.58  153.30
265                Buraidah      SA  26.33   43.98
290                   Sabha      LY  27.04   14.43
353                Dehlorān      IR  32.69   47.27
365                 Khanpur      PK  28.65   70.66
378             Mangrūl Pīr      IN  20.32   77.35
408   Los Llanos de Aridane      ES  28.66  -17.92
422         Charters Towers      AU -20.10  146.27
499                 Mae Sai      TH  20.43   99.88
515                  Karwar      IN  14.80   74.13
533                     Sur      OM  22.57   59.53
547                  Taunsa      PK  30.70   70.65
555         Tiznit Province      MA  29.58   -9.50
667                Valdivia      CL -39.81  -73.25
674                 Salalah      OM  17.02   54.09
737     Tando Muhammad Khan      PK  25.12   68.54
785                Saldanha      ZA -33.01   17.94
806          Victoria Point      AU -27.58  153.30
831                Buraidah      SA  26.33   43.98
856                   Sabha      LY  27.04   14.43
919                Dehlorān      IR  32.69   47.27
931                 Khanpur      PK  28.65   70.66
944             Mangrūl Pīr      IN  20.32   77.35
974   Los Llanos de Aridane      ES  28.66  -17.92
988         Charters Towers      AU -20.10  146.27
1065                Mae Sai      TH  20.43   99.88
1081                 Karwar      IN  14.80   74.13
1099                    Sur      OM  22.57   59.53
1113                 Taunsa      PK  30.70   70.65
1121        Tiznit Province      MA  29.58   -9.50

In [15]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

params = {"type" : "hotel",
          "keyword" : "hotel",
          "radius" : 5000,
          "key" : "Enter gkey"}

In [18]:
for index, row in hotel_df.iterrows():
    # get city name, lat, lnt from df
    lat = row["Lat"]
    lng = row["Lng"]
    city_name = row["City"]
    
    # add keyword to params dict
    params["location"] = f"{lat},{lng}"

    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {city_name}.")
    response = requests.get(base_url, params=params).json()
    
    # extract results
    results = response['results']
    
    # save the hotel name to dataframe
    try:
        print(f"Closest hotel in {city_name} is {results[0]['name']}.")
        hotel_df.loc[index, "Hotel Name"] = results[0]['name']

    # if there is no hotel available, show missing field
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")
    
    # Wait 1 sec to make another api request to avoid SSL Error
    time.sleep(1)

# Print end of search once searching is completed
print("-------End of Search-------")

Retrieving Results for Index 101: Valdivia.
Closest hotel in Valdivia is Hotel Naguilan.
------------
Retrieving Results for Index 108: Salalah.
Closest hotel in Salalah is HYATT SALALAH HOTEL.
------------
Retrieving Results for Index 171: Tando Muhammad Khan.
Closest hotel in Tando Muhammad Khan is Dilpasand Piyala Hotel.
------------
Retrieving Results for Index 219: Saldanha.
Closest hotel in Saldanha is Protea Hotel by Marriott Saldanha Bay.
------------
Retrieving Results for Index 240: Victoria Point.
Closest hotel in Victoria Point is Bay Retreat Motel.
------------
Retrieving Results for Index 265: Buraidah.
Closest hotel in Buraidah is فندق براند القصيم.
------------
Retrieving Results for Index 290: Sabha.
Closest hotel in Sabha is فندق علي.
------------
Retrieving Results for Index 353: Dehlorān.
Closest hotel in Dehlorān is هتل سعید.
------------
Retrieving Results for Index 365: Khanpur.
Closest hotel in Khanpur is Shakir Hotel & Bar BQ.
------------
Retrieving Results for Index 378: Mangrūl Pīr.
Missing field/result... skipping.
------------
Retrieving Results for Index 408: Los Llanos de Aridane.
Closest hotel in Los Llanos de Aridane is Hotel Hacienda de Abajo.
------------
Retrieving Results for Index 422: Charters Towers.
Closest hotel in Charters Towers is Commercial Hotel.
------------
Retrieving Results for Index 499: Mae Sai.
Closest hotel in Mae Sai is Nang Non Camping Ville.
------------
Retrieving Results for Index 515: Karwar.
Closest hotel in Karwar is Cintacor Island Resort.
------------
Retrieving Results for Index 533: Sur.
Closest hotel in Sur is Sur Plaza Hotel.
------------
Retrieving Results for Index 547: Taunsa.
Closest hotel in Taunsa is Hotel.
------------
Retrieving Results for Index 555: Tiznit Province.
Missing field/result... skipping.
------------
Retrieving Results for Index 667: Valdivia.
Closest hotel in Valdivia is Hotel Naguilan.
------------
Retrieving Results for Index 674: Salalah.
Closest hotel in Salalah is HYATT SALALAH HOTEL.
------------
Retrieving Results for Index 737: Tando Muhammad Khan.
Closest hotel in Tando Muhammad Khan is Dilpasand Piyala Hotel.
------------
Retrieving Results for Index 785: Saldanha.
Closest hotel in Saldanha is Protea Hotel by Marriott Saldanha Bay.
------------
Retrieving Results for Index 806: Victoria Point.
Closest hotel in Victoria Point is Bay Retreat Motel.
------------
Retrieving Results for Index 831: Buraidah.
Closest hotel in Buraidah is فندق براند القصيم.
------------
Retrieving Results for Index 856: Sabha.
Closest hotel in Sabha is فندق علي.
------------
Retrieving Results for Index 919: Dehlorān.
Closest hotel in Dehlorān is هتل سعید.
------------
Retrieving Results for Index 931: Khanpur.
Closest hotel in Khanpur is Shakir Hotel & Bar BQ.
------------
Retrieving Results for Index 944: Mangrūl Pīr.
Missing field/result... skipping.
------------
Retrieving Results for Index 974: Los Llanos de Aridane.
Closest hotel in Los Llanos de Aridane is Hotel Hacienda de Abajo.
------------
Retrieving Results for Index 988: Charters Towers.
Closest hotel in Charters Towers is Waverley Hotel.
------------
Retrieving Results for Index 1065: Mae Sai.
Closest hotel in Mae Sai is Nang Non Camping Ville.
------------
Retrieving Results for Index 1081: Karwar.
Closest hotel in Karwar is Cintacor Island Resort.
------------
Retrieving Results for Index 1099: Sur.
Closest hotel in Sur is Sur Plaza Hotel.
------------
Retrieving Results for Index 1113: Taunsa.
Closest hotel in Taunsa is Hotel.
------------
Retrieving Results for Index 1121: Tiznit Province.
Missing field/result... skipping.
------------
-------End of Search-------

In [19]:
# Display the hotel dataframe
hotel_df

,City,Country,Lat,Lng,Hotel Name
101,Valdivia,CL,-39.81,-73.25,Hotel Naguilan
108,Salalah,OM,17.02,54.09,HYATT SALALAH HOTEL
171,Tando Muhammad Khan,PK,25.12,68.54,Dilpasand Piyala Hotel
219,Saldanha,ZA,-33.01,17.94,Protea Hotel by Marriott Saldanha Bay
240,Victoria Point,AU,-27.58,153.30,Bay Retreat Motel
265,Buraidah,SA,26.33,43.98,فندق براند القصيم
290,Sabha,LY,27.04,14.43,فندق علي
353,Dehlorān,IR,32.69,47.27,هتل سعید
365,Khanpur,PK,28.65,70.66,Shakir Hotel & Bar BQ
378,Mangrūl Pīr,IN,20.32,77.35,
408,Los Llanos de Aridane,ES,28.66,-17.92,Hotel Hacienda de Abajo
422,Charters Towers,AU,-20.10,146.27,Commercial Hotel
499,Mae Sai,TH,20.43,99.88,Nang Non Camping Ville
515,Karwar,IN,14.80,74.13,Cintacor Island Resort
533,Sur,OM,22.57,59.53,Sur Plaza Hotel
547,Taunsa,PK,30.70,70.65,Hotel
555,Tiznit Province,MA,29.58,-9.50,
667,Valdivia,CL,-39.81,-73.25,Hotel Naguilan
674,Salalah,OM,17.02,54.09,HYATT SALALAH HOTEL
737,Tando Muhammad Khan,PK,25.12,68.54,Dilpasand Piyala Hotel
785,Saldanha,ZA,-33.01,17.94,Protea Hotel by Marriott Saldanha Bay
806,Victoria Point,AU,-27.58,153.30,Bay Retreat Motel
831,Buraidah,SA,26.33,43.98,فندق براند القصيم
856,Sabha,LY,27.04,14.43,فندق علي
919,Dehlorān,IR,32.69,47.27,هتل سعید
931,Khanpur,PK,28.65,70.66,Shakir Hotel & Bar BQ
944,Mangrūl Pīr,IN,20.32,77.35,
974,Los Llanos de Aridane,ES,28.66,-17.92,Hotel Hacienda de Abajo
988,Charters Towers,AU,-20.10,146.27,Waverley Hotel
1065,Mae Sai,TH,20.43,99.88,Nang Non Camping Ville
1081,Karwar,IN,14.80,74.13,Cintacor Island Resort
1099,Sur,OM,22.57,59.53,Sur Plaza Hotel
1113,Taunsa,PK,30.70,70.65,Hotel
1121,Tiznit Province,MA,29.58,-9.50,

In [21]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [22]:
# Add marker layer and info box content ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)

# Add the layer to the map
fig.add_layer(markers)

# Display Map
fig

Figure(layout=FigureLayout(height='420px'))